def copertina2():
    print("                              .     @$* @$3")
    print("                            '$Nueeed$$ed$$eeec$$")
    print("         ,            4$Lze@*$C2$b* ed(he*rb$CC$*$bc@$r")
    print("   /@ |~~            .e$$\"W$$B$B$**  ^$  e\"\"##d?$Bd$$$Nc. ..      @\\/~\\")
    print("   \\==|         4$kd*Cr$6F#\"`  **   .*==      # '\"**F#$I$b$*       |   I")
    print("      |         d$5N@$$\"   ....eu$$$$$$N$*$zbeuu     #$d$$$$b.     / @/")
    print("     @/     . z$Ted*\"$P zue$*9d$$$@#       W$e@B$$L.    \"#@$E$b@N")
    print("           #d$Id*P#  'Nd$$B$**\"       .*,     \"#*N$$b$c   $$$*$$c")
    print("          .d#+C6J   @@$B$*\"          -***-        \"#$$$$c   *$$$#$u")
    print("       ..u$l4@\"^\"zJ$7W*\"              '*`            ^*$@$$$r \"$\"E$@B>")
    print("       *@$l$P\"+Rd$$N#\"          *     /|\\     *        '\"$$$c.. ?E$*b")
    print("       z$ \"*.  .Jz$\"           ***   / | \\   ***         '*@N$b   d**N")
    print("     .z$JBR^bs@$$#          *   *   /  |  \\   *  *         \"$l*9N \"bN$Nee")
    print("    4$$.C*   dB@\"          ***    _/  /^\\  \\_   ***         '$$$z> 3$b$$#")
    print("     \"$\"$e$  @*$\"        *   *    \\\\^|   |^//    *   *        $$$u.^*$N$c")
    print("    JPd$%  @@d\"        ***        ***********       ***       '$Ni$  $EP$")
    print("  :e$\"*$  :et$          *         ***********        *         ^$$E  4$N$be")
    print("  ')$ud\"  @6$                                                   9$$   $*@$\"")
    print("   @F*$   *4P                       ./                          '$m#   .$$.")
    print("u*\"\"\"\"\"\"\"\"\"\"h                     ##=====                    e#\"\"\"\"\"\"\"\"\"#")
    print("E +e       ue. N                 ___##_______                 4F e=c     z*c")
    print("#e$@e.. ..z6+6d\"                #*************/               ^*cBe$u.  .$$@")
    print("   $ ^\"\"\"\" 4F\"  ze=eu              ********              z***hc ^\"$ \"\"*\"\" $")
    print("   $       ^F :*    3r                                  @\"  e \"b  $       $")
    print(" .e$        N $  'be$L...                            ...?be@F  $F $       9F")
    print("4\" $        $ $.  zm$*****h.                      ue\"\"\"\"*h6   J$\" $       4%")
    print("$  $        $ $$u5e\" .     \"k                    d\"       #$bu$F  $       4F")
    print("\"N $        $ ^d%P  dF      $  .            .e   $     -c  \"N$F  .$       4F")
    print(" #$$        $  $4*. \"N.    zP  3r ..    ..  $c   *u     $  u$K$  4F       4L")
    print("  ^N$e.     3  F$k*. \"*C$$$# .z$\" '$    4L  \"$c. '#$eeedF  $$$9r JF       J$")
    print("   $'\"$$eu. 4  F3\"K$ .e=*CB$$$$L .e$    '$bc.u$***hd6C\"\"  4kF$4F $F     u@$F")
    print("   $   '\"*$*@u N'L$B*\"z*\"\"     \"$F\" 4k 4c '7$\"      \"*$eu 4'L$J\" $   .e$*\"4F")
    print("   $      '\"hC*$ \"$#.P\"          $me$\"  #$*$       .  ^*INJL$\"$  $e$$*#   4F")
    print("   $         $b\"h \".F     $\"     ^F        $       9r   #L#$FJEd#C@\"      4L")
    print("  .$         $Jb   J\"..  4b      uF        *k      J%    #c^ $\" d$        4L")
    print(" :\"$         $k9   $ $%4c $Bme.ze$         '*$+eee@*$\"  :r$    @L$        4$")
    print(" $ $         $$Jr  $d\" '$r \"*==*\"            \"#**\"\" $r  4$3r  db$F        4F")
    print(" $c$         $'*F  $\"   '$            /\\            $    *(L  $$$F         k")
    print(" #i*e.       $ 4>  $  ue $         \\`.||.'/         'L c  $$ .L$d         .$")
    print("  \"b.\"*e.    4 4   $  $%db=eL     `.<\\||/>.'      e*+$/$r  $ '$\"$       .d$$")
    print("   $^#+cC*mu 4r4   4r:6@F  $$    -----++-----    <$. \"N?N  F  $ $    ud$$* $")
    print("   $    \"*eJ\"@L4   4k*3Ic.*\"      .'`.      #*5.J$$..F  $ $ ue#2*\"   $")
    print("   $       \"N.\"@r  4Fd\" '$r        /.'||`\\.        4$ '\"N*d\"  9.$#Ce*\"     $")
    print("   $         \"e^\"  'd\" uz$%           \\/           '$czr\"k#\"  4Pu@\"        $")

